### ISSUE TITLE
How to run the project locally? 

### ISSUE THREAD

**Issue by DanielPicarro** [jesimonbarreto/TeleoperatedCrane#1]
Hi!

I was wondering the how to run the project locally and couldn't figure it out on my own. Could you please explain the steps to be followed?
Besides that, could you please explain the purpose of each file?

Thanks in advance!

**Comment by jesimonbarreto** [comment]
Hello Daniel, 

The directories were organized. In addition, an execution topic has been added to the readme file.

Thank you for showing us this.
